global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jenkins"
    metrics_path: /prometheus/
    static_configs:
      - targets: ["jenkins:8080"]

  - job_name: "registry"
    static_configs:
      - targets: ["local-registry:5000"]
    metrics_path: /metrics

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
